server:
  port: 8081
spring.cloud.stream:
  function:
    definition: orderSupplier;paymentEventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-event1
    paymentEventConsumer-in-0:
      destination: payment-event1
